### ISSUE TITLE
Reduce toolbar height inside theme viewer

### ISSUE THREAD

**Issue by fandreuz** [stagfoo/tui-website#23]
Toolbar is too tall
![device-2017-09-03-215106](https://user-images.githubusercontent.com/8464342/30006144-06965952-90f2-11e7-9491-0e5848b8d4f6.png)

**Comment by stagfoo** [comment]
looks like its extra padding in the css
```css
.theme_preview .bottom-toolbar {    
     display: flex;
    clear: both;
    font-size: 1.5em;
    margin-bottom: 0.5em; // add this 
    margin-top: 0.5em; // add this
   // remove paddding
    text-align: center;
}
```
